application: simple
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

default_expiration: "365d"

handlers:
- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /gae/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: simple.py

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.template)|
 (.*/RCS/.*)|
 (\..*)|
 )$
